name: ci
on:
  push:
    branches:
      - main
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI CLI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: opentofu
          args: |
            init
            validate
            plan
            apply -auto-approve
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
